### ISSUE TITLE
Docs need updated to move params_from_vars to top of ci-cd-tooling.yml

### ISSUE THREAD

**Issue by tylerauerbeck** [rht-labs/enablement-docs#476]
In step 8 of the manual menace, we have:

```yaml

ci_cd:
  IMAGE_STREAM_NAMESPACE: "{{ ci_cd_namespace }}"

- object: ci-cd-builds
  content:
  - name: "jenkins-s2i-secret"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/secrets/secret-user-pass-plaintext.yml"
    params: "{{ playbook_dir }}/params/jenkins-s2i-secret"
    tags:
    - jenkins
  - name: "jenkins-s2i"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/jenkins-s2i-build/jenkins-s2i-build-template-with-secret.yml"
    params: "{{ playbook_dir }}/params/jenkins-s2i"
    params_from_vars: "{{ ci_cd }}"
    tags:
    - jenkins
  - name: "jenkins-slave-npm"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/imagestreams/imagestream-generic.yml"
    params: "{{ playbook_dir }}/params/jenkins-slave-npm"
    params_from_vars: "{{ ci_cd }}"
    tags:
    - jenkins
```

We should break these two pieces apart and have the user add `ci-cd:` to the top of the file. Otherwise this is causing users some issues because they're copying and pasting directly into the file and ansible hates it.
